/**
 * Payment provider abstraction.
 *
 * Nothing in the booking UI or server actions talks to a payment method
 * directly — everything goes through this interface. This is what makes it
 * possible to plug in real MTN MoMo Collections (or a card gateway) later by
 * writing ONE new class, without touching booking/appointment code.
 *
 * IMPORTANT / HONEST STATUS:
 * `MtnMomoProvider` below is an architectural stub only. It is shaped
 * exactly like the real MTN MoMo Collections API (create → poll status →
 * webhook confirms), but it does NOT call MTN's servers and does NOT move
 * real money. Wiring it to production requires:
 *   - An MTN MoMo Collections subscription (Ghana) with API user + API key
 *   - MTN_MOMO_* environment variables (see .env.example)
 *   - A publicly reachable HTTPS webhook endpoint for callbacks
 * Until those exist, only `CashProvider` (and manual card/bank recording by
 * staff) should be used in production. The system will refuse to mark a
 * MoMo payment "successful" from anything other than a verified provider
 * response — the browser reaching a "success" page is never sufficient.
 */

export type PaymentIntent = {
  appointmentId: string;
  amount: number;
  currency: string;
  paymentType: "deposit" | "final" | "full" | "refund";
  customerPhone: string;
};

export type PaymentAuthorization = {
  transactionReference: string; // our internal reference, always generated by us
  externalId: string; // what we told the provider
  providerTransactionId?: string; // what the provider gave back (if synchronous)
  status: "pending" | "successful" | "failed";
  raw?: unknown; // provider response metadata, stored as JSON — never secrets
};

export interface PaymentProvider {
  readonly name: "manual" | "mtn_momo" | "card_gateway";
  /** Starts a payment. For manual methods this immediately returns a
   * "pending" record for staff to confirm; for MoMo this would trigger a
   * prompt on the customer's phone. */
  createPayment(intent: PaymentIntent): Promise<PaymentAuthorization>;
  /** Server-side poll — NEVER trust a browser redirect as proof of payment. */
  getPaymentStatus(transactionReference: string): Promise<PaymentAuthorization["status"]>;
  /** Verifies and processes an inbound webhook/callback payload from the provider. */
  handleCallback(payload: unknown): Promise<PaymentAuthorization>;
  refundPayment(transactionReference: string, amount: number): Promise<PaymentAuthorization>;
}

function generateReference(prefix: string) {
  return `${prefix}-${Date.now()}-${crypto.randomUUID().slice(0, 8)}`;
}

/** Cash / in-person card / bank transfer recorded manually by staff at the
 * till. This is real and production-ready today — it's bookkeeping, not a
 * gateway, and requires no external credentials. */
export class ManualProvider implements PaymentProvider {
  readonly name = "manual" as const;

  async createPayment(intent: PaymentIntent): Promise<PaymentAuthorization> {
    return {
      transactionReference: generateReference("MAN"),
      externalId: intent.appointmentId,
      status: "successful", // manual payments are confirmed at the point staff records them
    };
  }
  async getPaymentStatus(): Promise<PaymentAuthorization["status"]> {
    return "successful";
  }
  async handleCallback(): Promise<PaymentAuthorization> {
    throw new Error("Manual provider does not receive callbacks.");
  }
  async refundPayment(transactionReference: string): Promise<PaymentAuthorization> {
    return { transactionReference, externalId: transactionReference, status: "successful" };
  }
}

/**
 * MTN MoMo Collections — ARCHITECTURAL STUB. See file-level comment.
 * Every method is written the way the real integration will need to work,
 * so swapping the body for real `fetch()` calls to MTN's sandbox/production
 * API is the only change required. It will throw if someone tries to use it
 * without configuring credentials, rather than pretending to succeed.
 */
export class MtnMomoProvider implements PaymentProvider {
  readonly name = "mtn_momo" as const;

  private configured() {
    return Boolean(
      process.env.MTN_MOMO_API_USER &&
        process.env.MTN_MOMO_API_KEY &&
        process.env.MTN_MOMO_SUBSCRIPTION_KEY
    );
  }

  async createPayment(intent: PaymentIntent): Promise<PaymentAuthorization> {
    if (!this.configured()) {
      throw new Error(
        `MTN MoMo is not configured (missing MTN_MOMO_API_USER / MTN_MOMO_API_KEY / ` +
          `MTN_MOMO_SUBSCRIPTION_KEY). Use the manual/cash flow, or configure production ` +
          `credentials before enabling MoMo at checkout for a GH₵${intent.amount} charge.`
      );
    }
    // --- Real integration would go here ---
    // const res = await fetch(`${process.env.MTN_MOMO_BASE_URL}/collection/v1_0/requesttopay`, {
    //   method: "POST",
    //   headers: { "X-Reference-Id": externalId, "Ocp-Apim-Subscription-Key": ..., Authorization: `Bearer ${token}` },
    //   body: JSON.stringify({ amount: intent.amount, currency: intent.currency, payer: { partyIdType: "MSISDN", partyId: intent.customerPhone } }),
    // });
    const externalId = generateReference("EXT");
    return {
      transactionReference: generateReference("MOMO"),
      externalId,
      status: "pending",
    };
  }

  async getPaymentStatus(): Promise<PaymentAuthorization["status"]> {
    if (!this.configured()) return "failed";
    // Real integration: GET /collection/v1_0/requesttopay/{referenceId}
    return "pending";
  }

  async handleCallback(payload: unknown): Promise<PaymentAuthorization> {
    // Real integration: verify the callback signature/IP allowlist per MTN's
    // docs before trusting ANY field in the payload.
    const body = payload as { referenceId?: string; status?: string; financialTransactionId?: string };
    if (!body?.referenceId) throw new Error("Invalid MoMo callback payload.");
    return {
      transactionReference: body.referenceId,
      externalId: body.referenceId,
      providerTransactionId: body.financialTransactionId,
      status: body.status === "SUCCESSFUL" ? "successful" : body.status === "FAILED" ? "failed" : "pending",
      raw: { status: body.status }, // do not persist full raw payloads that may include PII/secrets
    };
  }

  async refundPayment(transactionReference: string): Promise<PaymentAuthorization> {
    if (!this.configured()) {
      throw new Error("MTN MoMo is not configured; cannot process refund.");
    }
    // Real integration: POST /disbursement/v1_0/refund
    return { transactionReference, externalId: transactionReference, status: "pending" };
  }
}

export function getPaymentProvider(method: "cash" | "mobile_money" | "card" | "bank_transfer"): PaymentProvider {
  if (method === "mobile_money") return new MtnMomoProvider();
  return new ManualProvider(); // cash, card (in-person), bank transfer are all staff-recorded today
}

/** Computes the required booking deposit per current salon settings
 * (flat GH₵ amount by default, or a percentage of the service price). */
export function computeDeposit(
  servicePrice: number,
  settings: { depositEnabled: boolean; depositMode: "flat" | "percent"; depositFlatAmount: number; depositPercent: number }
): number {
  if (!settings.depositEnabled) return 0;
  if (settings.depositMode === "percent") {
    return Math.round(((servicePrice * settings.depositPercent) / 100) * 100) / 100;
  }
  return Math.min(settings.depositFlatAmount, servicePrice);
}
